// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCompressor creates a new instance of MockCompressor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompressor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompressor {
	mock := &MockCompressor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCompressor is an autogenerated mock type for the Compressor type
type MockCompressor struct {
	mock.Mock
}

type MockCompressor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompressor) EXPECT() *MockCompressor_Expecter {
	return &MockCompressor_Expecter{mock: &_m.Mock}
}

// Encoding provides a mock function for the type MockCompressor
func (_mock *MockCompressor) Encoding() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Encoding")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCompressor_Encoding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encoding'
type MockCompressor_Encoding_Call struct {
	*mock.Call
}

// Encoding is a helper method to define mock.On call
func (_e *MockCompressor_Expecter) Encoding() *MockCompressor_Encoding_Call {
	return &MockCompressor_Encoding_Call{Call: _e.mock.On("Encoding")}
}

func (_c *MockCompressor_Encoding_Call) Run(run func()) *MockCompressor_Encoding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCompressor_Encoding_Call) Return(s string) *MockCompressor_Encoding_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCompressor_Encoding_Call) RunAndReturn(run func() string) *MockCompressor_Encoding_Call {
	_c.Call.Return(run)
	return _c
}

// NewReader provides a mock function for the type MockCompressor
func (_mock *MockCompressor) NewReader(r io.Reader) (io.ReadCloser, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for NewReader")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader) (io.ReadCloser, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(io.Reader) io.ReadCloser); ok {
		r0 = returnFunc(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompressor_NewReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewReader'
type MockCompressor_NewReader_Call struct {
	*mock.Call
}

// NewReader is a helper method to define mock.On call
//   - r io.Reader
func (_e *MockCompressor_Expecter) NewReader(r interface{}) *MockCompressor_NewReader_Call {
	return &MockCompressor_NewReader_Call{Call: _e.mock.On("NewReader", r)}
}

func (_c *MockCompressor_NewReader_Call) Run(run func(r io.Reader)) *MockCompressor_NewReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCompressor_NewReader_Call) Return(readCloser io.ReadCloser, err error) *MockCompressor_NewReader_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockCompressor_NewReader_Call) RunAndReturn(run func(r io.Reader) (io.ReadCloser, error)) *MockCompressor_NewReader_Call {
	_c.Call.Return(run)
	return _c
}

// NewWriter provides a mock function for the type MockCompressor
func (_mock *MockCompressor) NewWriter(w io.Writer) (io.WriteCloser, error) {
	ret := _mock.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for NewWriter")
	}

	var r0 io.WriteCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(io.Writer) (io.WriteCloser, error)); ok {
		return returnFunc(w)
	}
	if returnFunc, ok := ret.Get(0).(func(io.Writer) io.WriteCloser); ok {
		r0 = returnFunc(w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(io.Writer) error); ok {
		r1 = returnFunc(w)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompressor_NewWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWriter'
type MockCompressor_NewWriter_Call struct {
	*mock.Call
}

// NewWriter is a helper method to define mock.On call
//   - w io.Writer
func (_e *MockCompressor_Expecter) NewWriter(w interface{}) *MockCompressor_NewWriter_Call {
	return &MockCompressor_NewWriter_Call{Call: _e.mock.On("NewWriter", w)}
}

func (_c *MockCompressor_NewWriter_Call) Run(run func(w io.Writer)) *MockCompressor_NewWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCompressor_NewWriter_Call) Return(writeCloser io.WriteCloser, err error) *MockCompressor_NewWriter_Call {
	_c.Call.Return(writeCloser, err)
	return _c
}

func (_c *MockCompressor_NewWriter_Call) RunAndReturn(run func(w io.Writer) (io.WriteCloser, error)) *MockCompressor_NewWriter_Call {
	_c.Call.Return(run)
	return _c
}
