// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kkolyasik/gophermart/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccrualStorage creates a new instance of MockAccrualStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccrualStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccrualStorage {
	mock := &MockAccrualStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccrualStorage is an autogenerated mock type for the AccrualStorage type
type MockAccrualStorage struct {
	mock.Mock
}

type MockAccrualStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccrualStorage) EXPECT() *MockAccrualStorage_Expecter {
	return &MockAccrualStorage_Expecter{mock: &_m.Mock}
}

// CompleteOrder provides a mock function for the type MockAccrualStorage
func (_mock *MockAccrualStorage) CompleteOrder(ctx context.Context, uid uuid.UUID, number string, status model.Status, accrual *float64) error {
	ret := _mock.Called(ctx, uid, number, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, model.Status, *float64) error); ok {
		r0 = returnFunc(ctx, uid, number, status, accrual)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccrualStorage_CompleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteOrder'
type MockAccrualStorage_CompleteOrder_Call struct {
	*mock.Call
}

// CompleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
//   - number string
//   - status model.Status
//   - accrual *float64
func (_e *MockAccrualStorage_Expecter) CompleteOrder(ctx interface{}, uid interface{}, number interface{}, status interface{}, accrual interface{}) *MockAccrualStorage_CompleteOrder_Call {
	return &MockAccrualStorage_CompleteOrder_Call{Call: _e.mock.On("CompleteOrder", ctx, uid, number, status, accrual)}
}

func (_c *MockAccrualStorage_CompleteOrder_Call) Run(run func(ctx context.Context, uid uuid.UUID, number string, status model.Status, accrual *float64)) *MockAccrualStorage_CompleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 model.Status
		if args[3] != nil {
			arg3 = args[3].(model.Status)
		}
		var arg4 *float64
		if args[4] != nil {
			arg4 = args[4].(*float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAccrualStorage_CompleteOrder_Call) Return(err error) *MockAccrualStorage_CompleteOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccrualStorage_CompleteOrder_Call) RunAndReturn(run func(ctx context.Context, uid uuid.UUID, number string, status model.Status, accrual *float64) error) *MockAccrualStorage_CompleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnprocessedOrders provides a mock function for the type MockAccrualStorage
func (_mock *MockAccrualStorage) GetUnprocessedOrders(ctx context.Context) ([]model.Order, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnprocessedOrders")
	}

	var r0 []model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Order, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Order); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccrualStorage_GetUnprocessedOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnprocessedOrders'
type MockAccrualStorage_GetUnprocessedOrders_Call struct {
	*mock.Call
}

// GetUnprocessedOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccrualStorage_Expecter) GetUnprocessedOrders(ctx interface{}) *MockAccrualStorage_GetUnprocessedOrders_Call {
	return &MockAccrualStorage_GetUnprocessedOrders_Call{Call: _e.mock.On("GetUnprocessedOrders", ctx)}
}

func (_c *MockAccrualStorage_GetUnprocessedOrders_Call) Run(run func(ctx context.Context)) *MockAccrualStorage_GetUnprocessedOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccrualStorage_GetUnprocessedOrders_Call) Return(orders []model.Order, err error) *MockAccrualStorage_GetUnprocessedOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockAccrualStorage_GetUnprocessedOrders_Call) RunAndReturn(run func(ctx context.Context) ([]model.Order, error)) *MockAccrualStorage_GetUnprocessedOrders_Call {
	_c.Call.Return(run)
	return _c
}
