// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kkolyasik/gophermart/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccrualProvider creates a new instance of MockAccrualProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccrualProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccrualProvider {
	mock := &MockAccrualProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccrualProvider is an autogenerated mock type for the AccrualProvider type
type MockAccrualProvider struct {
	mock.Mock
}

type MockAccrualProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccrualProvider) EXPECT() *MockAccrualProvider_Expecter {
	return &MockAccrualProvider_Expecter{mock: &_m.Mock}
}

// GetOrderAccrual provides a mock function for the type MockAccrualProvider
func (_mock *MockAccrualProvider) GetOrderAccrual(ctx context.Context, orderNumber string) (model.AccrualResponse, error) {
	ret := _mock.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderAccrual")
	}

	var r0 model.AccrualResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.AccrualResponse, error)); ok {
		return returnFunc(ctx, orderNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.AccrualResponse); ok {
		r0 = returnFunc(ctx, orderNumber)
	} else {
		r0 = ret.Get(0).(model.AccrualResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccrualProvider_GetOrderAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderAccrual'
type MockAccrualProvider_GetOrderAccrual_Call struct {
	*mock.Call
}

// GetOrderAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *MockAccrualProvider_Expecter) GetOrderAccrual(ctx interface{}, orderNumber interface{}) *MockAccrualProvider_GetOrderAccrual_Call {
	return &MockAccrualProvider_GetOrderAccrual_Call{Call: _e.mock.On("GetOrderAccrual", ctx, orderNumber)}
}

func (_c *MockAccrualProvider_GetOrderAccrual_Call) Run(run func(ctx context.Context, orderNumber string)) *MockAccrualProvider_GetOrderAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccrualProvider_GetOrderAccrual_Call) Return(accrualResponse model.AccrualResponse, err error) *MockAccrualProvider_GetOrderAccrual_Call {
	_c.Call.Return(accrualResponse, err)
	return _c
}

func (_c *MockAccrualProvider_GetOrderAccrual_Call) RunAndReturn(run func(ctx context.Context, orderNumber string) (model.AccrualResponse, error)) *MockAccrualProvider_GetOrderAccrual_Call {
	_c.Call.Return(run)
	return _c
}
