// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kkolyasik/gophermart/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderStorage creates a new instance of MockOrderStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderStorage {
	mock := &MockOrderStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderStorage is an autogenerated mock type for the OrderStorage type
type MockOrderStorage struct {
	mock.Mock
}

type MockOrderStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderStorage) EXPECT() *MockOrderStorage_Expecter {
	return &MockOrderStorage_Expecter{mock: &_m.Mock}
}

// CompleteOrder provides a mock function for the type MockOrderStorage
func (_mock *MockOrderStorage) CompleteOrder(ctx context.Context, uid uuid.UUID, number string, status model.Status, accrual *float64) error {
	ret := _mock.Called(ctx, uid, number, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, model.Status, *float64) error); ok {
		r0 = returnFunc(ctx, uid, number, status, accrual)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderStorage_CompleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteOrder'
type MockOrderStorage_CompleteOrder_Call struct {
	*mock.Call
}

// CompleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
//   - number string
//   - status model.Status
//   - accrual *float64
func (_e *MockOrderStorage_Expecter) CompleteOrder(ctx interface{}, uid interface{}, number interface{}, status interface{}, accrual interface{}) *MockOrderStorage_CompleteOrder_Call {
	return &MockOrderStorage_CompleteOrder_Call{Call: _e.mock.On("CompleteOrder", ctx, uid, number, status, accrual)}
}

func (_c *MockOrderStorage_CompleteOrder_Call) Run(run func(ctx context.Context, uid uuid.UUID, number string, status model.Status, accrual *float64)) *MockOrderStorage_CompleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 model.Status
		if args[3] != nil {
			arg3 = args[3].(model.Status)
		}
		var arg4 *float64
		if args[4] != nil {
			arg4 = args[4].(*float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockOrderStorage_CompleteOrder_Call) Return(err error) *MockOrderStorage_CompleteOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderStorage_CompleteOrder_Call) RunAndReturn(run func(ctx context.Context, uid uuid.UUID, number string, status model.Status, accrual *float64) error) *MockOrderStorage_CompleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type MockOrderStorage
func (_mock *MockOrderStorage) CreateOrder(ctx context.Context, uid uuid.UUID, number string) error {
	ret := _mock.Called(ctx, uid, number)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, uid, number)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderStorage_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderStorage_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
//   - number string
func (_e *MockOrderStorage_Expecter) CreateOrder(ctx interface{}, uid interface{}, number interface{}) *MockOrderStorage_CreateOrder_Call {
	return &MockOrderStorage_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, uid, number)}
}

func (_c *MockOrderStorage_CreateOrder_Call) Run(run func(ctx context.Context, uid uuid.UUID, number string)) *MockOrderStorage_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderStorage_CreateOrder_Call) Return(err error) *MockOrderStorage_CreateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderStorage_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, uid uuid.UUID, number string) error) *MockOrderStorage_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByNumber provides a mock function for the type MockOrderStorage
func (_mock *MockOrderStorage) GetOrderByNumber(ctx context.Context, number string) (model.Order, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByNumber")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = returnFunc(ctx, number)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderStorage_GetOrderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByNumber'
type MockOrderStorage_GetOrderByNumber_Call struct {
	*mock.Call
}

// GetOrderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *MockOrderStorage_Expecter) GetOrderByNumber(ctx interface{}, number interface{}) *MockOrderStorage_GetOrderByNumber_Call {
	return &MockOrderStorage_GetOrderByNumber_Call{Call: _e.mock.On("GetOrderByNumber", ctx, number)}
}

func (_c *MockOrderStorage_GetOrderByNumber_Call) Run(run func(ctx context.Context, number string)) *MockOrderStorage_GetOrderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderStorage_GetOrderByNumber_Call) Return(order model.Order, err error) *MockOrderStorage_GetOrderByNumber_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderStorage_GetOrderByNumber_Call) RunAndReturn(run func(ctx context.Context, number string) (model.Order, error)) *MockOrderStorage_GetOrderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnprocessedOrders provides a mock function for the type MockOrderStorage
func (_mock *MockOrderStorage) GetUnprocessedOrders(ctx context.Context) ([]model.Order, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnprocessedOrders")
	}

	var r0 []model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Order, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Order); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderStorage_GetUnprocessedOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnprocessedOrders'
type MockOrderStorage_GetUnprocessedOrders_Call struct {
	*mock.Call
}

// GetUnprocessedOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderStorage_Expecter) GetUnprocessedOrders(ctx interface{}) *MockOrderStorage_GetUnprocessedOrders_Call {
	return &MockOrderStorage_GetUnprocessedOrders_Call{Call: _e.mock.On("GetUnprocessedOrders", ctx)}
}

func (_c *MockOrderStorage_GetUnprocessedOrders_Call) Run(run func(ctx context.Context)) *MockOrderStorage_GetUnprocessedOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderStorage_GetUnprocessedOrders_Call) Return(orders []model.Order, err error) *MockOrderStorage_GetUnprocessedOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderStorage_GetUnprocessedOrders_Call) RunAndReturn(run func(ctx context.Context) ([]model.Order, error)) *MockOrderStorage_GetUnprocessedOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserOrders provides a mock function for the type MockOrderStorage
func (_mock *MockOrderStorage) GetUserOrders(ctx context.Context, uid uuid.UUID) ([]model.Order, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrders")
	}

	var r0 []model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Order, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Order); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderStorage_GetUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrders'
type MockOrderStorage_GetUserOrders_Call struct {
	*mock.Call
}

// GetUserOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
func (_e *MockOrderStorage_Expecter) GetUserOrders(ctx interface{}, uid interface{}) *MockOrderStorage_GetUserOrders_Call {
	return &MockOrderStorage_GetUserOrders_Call{Call: _e.mock.On("GetUserOrders", ctx, uid)}
}

func (_c *MockOrderStorage_GetUserOrders_Call) Run(run func(ctx context.Context, uid uuid.UUID)) *MockOrderStorage_GetUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderStorage_GetUserOrders_Call) Return(orders []model.Order, err error) *MockOrderStorage_GetUserOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderStorage_GetUserOrders_Call) RunAndReturn(run func(ctx context.Context, uid uuid.UUID) ([]model.Order, error)) *MockOrderStorage_GetUserOrders_Call {
	_c.Call.Return(run)
	return _c
}
