// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderValidator creates a new instance of MockOrderValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderValidator {
	mock := &MockOrderValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderValidator is an autogenerated mock type for the OrderValidator type
type MockOrderValidator struct {
	mock.Mock
}

type MockOrderValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderValidator) EXPECT() *MockOrderValidator_Expecter {
	return &MockOrderValidator_Expecter{mock: &_m.Mock}
}

// Valid provides a mock function for the type MockOrderValidator
func (_mock *MockOrderValidator) Valid(number string) bool {
	ret := _mock.Called(number)

	if len(ret) == 0 {
		panic("no return value specified for Valid")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(number)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockOrderValidator_Valid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Valid'
type MockOrderValidator_Valid_Call struct {
	*mock.Call
}

// Valid is a helper method to define mock.On call
//   - number string
func (_e *MockOrderValidator_Expecter) Valid(number interface{}) *MockOrderValidator_Valid_Call {
	return &MockOrderValidator_Valid_Call{Call: _e.mock.On("Valid", number)}
}

func (_c *MockOrderValidator_Valid_Call) Run(run func(number string)) *MockOrderValidator_Valid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderValidator_Valid_Call) Return(b bool) *MockOrderValidator_Valid_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockOrderValidator_Valid_Call) RunAndReturn(run func(number string) bool) *MockOrderValidator_Valid_Call {
	_c.Call.Return(run)
	return _c
}
