// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kkolyasik/gophermart/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBalanceService creates a new instance of MockBalanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceService {
	mock := &MockBalanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBalanceService is an autogenerated mock type for the BalanceService type
type MockBalanceService struct {
	mock.Mock
}

type MockBalanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceService) EXPECT() *MockBalanceService_Expecter {
	return &MockBalanceService_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function for the type MockBalanceService
func (_mock *MockBalanceService) GetBalance(ctx context.Context, uid uuid.UUID) (model.Balance, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 model.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Balance, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Balance); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		r0 = ret.Get(0).(model.Balance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockBalanceService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
func (_e *MockBalanceService_Expecter) GetBalance(ctx interface{}, uid interface{}) *MockBalanceService_GetBalance_Call {
	return &MockBalanceService_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, uid)}
}

func (_c *MockBalanceService_GetBalance_Call) Run(run func(ctx context.Context, uid uuid.UUID)) *MockBalanceService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceService_GetBalance_Call) Return(balance model.Balance, err error) *MockBalanceService_GetBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockBalanceService_GetBalance_Call) RunAndReturn(run func(ctx context.Context, uid uuid.UUID) (model.Balance, error)) *MockBalanceService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawals provides a mock function for the type MockBalanceService
func (_mock *MockBalanceService) GetWithdrawals(ctx context.Context, uid uuid.UUID) ([]model.Withdraw, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawals")
	}

	var r0 []model.Withdraw
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Withdraw, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Withdraw); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdraw)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceService_GetWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawals'
type MockBalanceService_GetWithdrawals_Call struct {
	*mock.Call
}

// GetWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
func (_e *MockBalanceService_Expecter) GetWithdrawals(ctx interface{}, uid interface{}) *MockBalanceService_GetWithdrawals_Call {
	return &MockBalanceService_GetWithdrawals_Call{Call: _e.mock.On("GetWithdrawals", ctx, uid)}
}

func (_c *MockBalanceService_GetWithdrawals_Call) Run(run func(ctx context.Context, uid uuid.UUID)) *MockBalanceService_GetWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceService_GetWithdrawals_Call) Return(withdraws []model.Withdraw, err error) *MockBalanceService_GetWithdrawals_Call {
	_c.Call.Return(withdraws, err)
	return _c
}

func (_c *MockBalanceService_GetWithdrawals_Call) RunAndReturn(run func(ctx context.Context, uid uuid.UUID) ([]model.Withdraw, error)) *MockBalanceService_GetWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockBalanceService
func (_mock *MockBalanceService) Withdraw(ctx context.Context, uid uuid.UUID, sum float64, number string) error {
	ret := _mock.Called(ctx, uid, sum, number)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, float64, string) error); ok {
		r0 = returnFunc(ctx, uid, sum, number)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBalanceService_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockBalanceService_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
//   - sum float64
//   - number string
func (_e *MockBalanceService_Expecter) Withdraw(ctx interface{}, uid interface{}, sum interface{}, number interface{}) *MockBalanceService_Withdraw_Call {
	return &MockBalanceService_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, uid, sum, number)}
}

func (_c *MockBalanceService_Withdraw_Call) Run(run func(ctx context.Context, uid uuid.UUID, sum float64, number string)) *MockBalanceService_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBalanceService_Withdraw_Call) Return(err error) *MockBalanceService_Withdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBalanceService_Withdraw_Call) RunAndReturn(run func(ctx context.Context, uid uuid.UUID, sum float64, number string) error) *MockBalanceService_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}
