// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthStorage creates a new instance of MockAuthStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthStorage {
	mock := &MockAuthStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthStorage is an autogenerated mock type for the AuthStorage type
type MockAuthStorage struct {
	mock.Mock
}

type MockAuthStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthStorage) EXPECT() *MockAuthStorage_Expecter {
	return &MockAuthStorage_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthStorage
func (_mock *MockAuthStorage) Login(ctx context.Context, login string) (uuid.UUID, string, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 uuid.UUID
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, string, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, login)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthStorage_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthStorage_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockAuthStorage_Expecter) Login(ctx interface{}, login interface{}) *MockAuthStorage_Login_Call {
	return &MockAuthStorage_Login_Call{Call: _e.mock.On("Login", ctx, login)}
}

func (_c *MockAuthStorage_Login_Call) Run(run func(ctx context.Context, login string)) *MockAuthStorage_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthStorage_Login_Call) Return(uUID uuid.UUID, s string, err error) *MockAuthStorage_Login_Call {
	_c.Call.Return(uUID, s, err)
	return _c
}

func (_c *MockAuthStorage_Login_Call) RunAndReturn(run func(ctx context.Context, login string) (uuid.UUID, string, error)) *MockAuthStorage_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthStorage
func (_mock *MockAuthStorage) Register(ctx context.Context, login string, hash string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, login, hash)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, login, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, login, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthStorage_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthStorage_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - hash string
func (_e *MockAuthStorage_Expecter) Register(ctx interface{}, login interface{}, hash interface{}) *MockAuthStorage_Register_Call {
	return &MockAuthStorage_Register_Call{Call: _e.mock.On("Register", ctx, login, hash)}
}

func (_c *MockAuthStorage_Register_Call) Run(run func(ctx context.Context, login string, hash string)) *MockAuthStorage_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthStorage_Register_Call) Return(uUID uuid.UUID, err error) *MockAuthStorage_Register_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockAuthStorage_Register_Call) RunAndReturn(run func(ctx context.Context, login string, hash string) (uuid.UUID, error)) *MockAuthStorage_Register_Call {
	_c.Call.Return(run)
	return _c
}
